### ISSUE TITLE
MeCabUniDicNode is incompatible with UniDic 2.2.0 or later

### ISSUE THREAD

**Issue by AlissaSabre** [komutan/NMeCab#15]
When using UniDic 2.3.0 (the latest version released on 2018) with NMeCab, some feature properties return wrong values.  In particular, Kana, KanaBase, Form, FormBase, IConType, FConType, AType, AConType, and AModType are wrong.

I believe it is due to UniDic's breaking change on its feature layout made between UniDic 2.1.2 and 2.2.0.  The new layout used in the recent releases are called "node-format-unidic22" in their dicrc file.  As a result, when using the binary dictionary files distributed by NINJAL, the MeCabUniDicNode properties mentioned above return wrong values if the version of the UniDic is 2.2.0 or later.

I believe MeCabUniDicNode should be updated to support node-format-unidic22 (or, alternatively, another type, e.g., MeCabUniDic22Node, be added, preserving the existing type for the older versions of UniDic.)

**Comment by komutan** [comment]
@AlissaSabre 
Thank you good report, again!
I didn’t know the change on between UniDic 2.1.2 and 2.2.0.
I was saved.
I’ll check and update function.

**Comment by komutan** [comment]
@AlissaSabre さん
プルリクエストありがとうございます。マージさせて頂きました。

それと、私としてテストコードの追加を行いました。そのためにUniDicのバイナリもリポジトリに追加しています。（これにはgit lfsを使っています。）

それとクラス名は、最初のほうでご提案いただいた「MeCabUniDic22～」にしました。これは、今後もUniDicの素性フォーマットが変わってしまうことを見越し、あくまで特定のUniDicバージョンに限定することを明示したいからです。

また、それにあわせ、過去の素性フォーマットのものも「MeCabUniDic21～」として再追加しました。

@AlissaSabre さんのご協力に感謝します。
本件はこれでクローズしたいと思います。
