### ISSUE TITLE
Tagger creation throws IOException if another process uses the same dictionary in NMeCab

### ISSUE THREAD

**Issue by AlissaSabre** [komutan/NMeCab#17]
A Tagger creation method, such as `NMeCabIpaDic.CreateTagger()` or `MeCabUniDicTagger.Create(string)`, throws IOException if another process is using the same set of dictionary files through NMeCab library.  Considering the fact that NMeCab never updates/writes to dictionary files, I think the library should allow sharing of the same dictionary files between multiple processes.

Reproduction steps:
1. Run my [NMeCabDemo](https://github.com/AlissaSabre/NMeCabDemo) program by double clicking on the file NMeCabDemo.exe.  The window of the program opens.
2. Double click on the same file again while the first application window is still open.

Expected behaviour:
The second application window opens.

Observed behaviour:
A message box showing an IOException opens.

(Note that you need to use the latest version (v1.0.2) of the NMeCabDemo program to verify the above reproduction steps, because earlier versions included a bug to _ignore_ the Exception during initialization...)

**Comment by komutan** [comment]
@AlissaSabre さん
gitやプルリクエスト関係で、ごちゃごちゃ操作してしまってすみません。
また、長い時間かかりすみません。
ユニットテストでもパフォーマンステストでも問題は見られず、これが複数プロセスからの使用時の問題の改善になることは間違いないであろうことから、いただいたプルリクエストを取り込みました。
また、コードが少し込み入ってきたので、一元化するクラスを作ってそこに委譲するようにしました。
後ほどNuGetへもリリースしたいと思います。（0.10.0-bata3としても新バージョンだとNuGetから認識されないでしょうから、0.10.0-RC1にします）

ご協力に感謝します！

**Comment by AlissaSabre** [comment]
> （0.10.0-bata3としても新バージョンだとNuGetから認識されないでしょうから、0.10.0-RC1にします）

これはおそらく、-bata2 としてリリースなさったものが、NuGet で「-beta」よりも新しいものとみなされなかった問題のことを言っているのだと思いますが、それは、b の次が「a」になっていたことが原因です。「-beta2」であれば（2 の前にピリオドがあろうとなかろうと）「-beta」よりも新しいものとみなされます。

なお、まさかと思いますが、今回のコメントでも「-bata3」とお書きになっていますので、ひょっとすると何らかの理由で「bata」と呼ぶことを意図しており、alpha の次のリリースの時点で誤って「beta」としてしまったのかもしれませんが、その場合は、「-bata なんちゃら」はすべて「-beta」よりも古いものと見なされますので、次の枝（-gamma なり -tata なり -RC なり）に飛ぶしかありません。

以上、僭越ながら。

**Comment by komutan** [comment]
コメントありがとうございます！
なるほどスペルミスです。気づいていませんでした。。
