### ISSUE TITLE
publish to nuget

### ISSUE THREAD

**Issue by komutan** [komutan/NMeCab#2]
まずは以下のαバージョン
- ライブラリ本体のみのパッケージ
— nmecabというnuget idは既に使用されていたので、libnmecabで。
— sdk形式プロジェクトファイルによりビルド
- ipadic付きパッケージ
— 上記ライブラリ本体と依存するが、別のパッケージとする
— 辞書ファイルを意識せず、静的メソッドでTaggerインスタンスを生成するだけで使用可能にする
— @kekyo 氏が、素晴らしいノウハウと更にソースコードも公開されているので、OSSとして流用させて頂く。

**Comment by kekyo** [comment]
元コードNMeCabの公開ありがとうございます！ これがなければ簡単に使うことが出来ませんでした。一部でも本体に還元して貰えるのは大歓迎です 🤩

**Comment by komutan** [comment]
@kekyo さん ありがとうございます！
早速にコメント頂けるとは！！
おかげでヤル気が湧いてきました！

**Comment by komutan** [comment]
とりあえずα版はNuGet公開済み。
