### ISSUE TITLE
Missing BSD file?

### ISSUE THREAD

**Issue by k-takio** [komutan/NMeCab#26]
COPYINGファイルにBSDライセンスの記載がありますが、実体となるBSDファイルがないようです。

MeCabと同じ形態であれば下記のファイルと同等でしょうか？
オリジナルのBSD（四条項）なのか、修正BSD（三条項）なのかが不明だったので登録させていただきました。

https://github.com/taku910/mecab/blob/master/mecab/BSD

**Comment by komutan** [comment]
COPYINGファイルに記載していますが、NMeCabはGPLもしくはLGPLライセンスの元で公開しています。

MeCabのほうでは、最初はGPL/LGPLだったところ、途中からGPL/LGPL/BSDに変更しています。しかしMeCabの作者は、これを後悔している旨のコメントをしています。
BSDという制約の緩いライセンスに一度変更すると、元に戻すことはできなくなります。
そのためNMeCabでは今のところGPL/LGPLだけを受け継いでいます。

BSDファイルを置いていないのは、このためです。

NMeCabはGPLもしくはLGPLライセンスで使用するようお願いします。

NMeCabのCOPYINGファイル：
https://github.com/komutan/NMeCab/blob/master/COPYING

参考「LGPL の利用規約について」：
https://ja.osdn.net/projects/nmecab/forums/24964/28263/

**Comment by komutan** [comment]
追伸
COPYING内のMeCabについての記述（MeCabのCOPYINGの転載）から、「(see the file BSD)」を除去しました。

https://github.com/komutan/NMeCab/commit/264015565bb20ecdfde07bae863a29cca383687f
