### ISSUE TITLE
入力文字数が多いとtoo long sentence. という例外が発生する

### ISSUE THREAD

**Issue by sseiichi** [komutan/NMeCab#27]
300,000文字～650,000文字以上のstringを
MeCabTaggerのParseToNode()メソッドに入力すると
"too long sentence. "というメッセージの例外が発生します。

とりあえず入力文字列を分割して回避したのですが、
エレガントな解決方法があれば教えてください。

ちなみに例外が発生する文字数の閾値は
半角文字と全角文字の割合に依存しているようです。
英語の文章だと650,000文字程度のstringでも例外が発生しません。
日本語の文章だと上限の文字数が小さくなるようです。

**Comment by komutan** [comment]
@sseiichi さん
鋭いご質問をありがとうございます。
すでに実施していらっしゃるとおり「入力文字列を分割する」というのが、最もよい解決方法だと思います。

NMeCabは最小コスト法という形態素解析手法を使っており、「経路上の単語の生起コストと連結コストの和＝累積コスト」が最も小さくなる経路を探すことで解を得ています。累積コストがオーバーフローを起こせばそもそも解析不能になることや、可能性のある経路が多くなり負荷が上がりすぎることから、解析途中に閾値を超える累積コストしか得られなくなったら、"too long sentence. "というメッセージの例外をスローしています。
この閾値を今より大きくすることもできますが、根本的な解決にならず、益はあまりないと思います。
（例外をスローする仕様については、改善の余地がありそうなので考えたいと思います。）

生起コストと連結コストがInt16で辞書に登録されており、累積コストの閾値はInt32の最大値にしていることから、大まかに計算すると16,384単語以上なら例外になる可能性があります。
単語数に依存する性質ですが、日本語は1文字で単語になるケースが多くあるので、実際上は文字数で入力を制限するとよいです。

英語の文章で閾値を超え難いことは、ご指摘の通りです。
実証していただいて大変ありがたく思います。

ご覧になる他の方のため、サンプルを示します。
```csharp
var results = text
              .Split(new[] { '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries) // 改行で分割
              .Select(s => s.Substring(0, Math.Min(s.Length, int.MaxValue / 4))) // 分割後も文字数を制約
              .SelectMany(s => tagger.Parse(s)); // 分割したものをそれぞれに解析
```

**Comment by komutan** [comment]
↑すみません。数字を訂正しました。

**Comment by sseiichi** [comment]
ご丁寧な回答ありがとうございます。
今までどおり入力文字列を分割することにします。
