### ISSUE TITLE
Option to modify IpaDic folder path

### ISSUE THREAD

**Issue by Mario1159** [komutan/NMeCab#31]
It's there a way to change the folder path where the IpaDic files are located when adding the library as PackageReference in the project file?

**Comment by komutan** [comment]
If "the folder path" is "the dictionary files path", you can specify it as follows.

```
var dicDir = @"C:\Program Files (x86)\MeCab\dic\ipadic"; // dictionary files path

using (var tagger = MeCabIpaDicTagger.Create(dicDir)) // create Tagger for ipadic
{
```

**Comment by Mario1159** [comment]
I don't mean the path where I can read the dictionary files, I meant the path in which the dictionary files are "created", that's by default the output directory when I build the project, and I don't know if there is a way to change it in my own project where I have this library included instead of changing directly the [LibNMeCab.IpaDicBin project file](https://github.com/komutan/NMeCab/blob/master/src/LibNMeCab.IpaDicBin/LibNMeCab.IpaDicBin.csproj)

**Comment by komutan** [comment]
Is that the situation when you install "LibNMeCab.IpaDicBin" with Nuget? Do you want to specify the path of the dictionary files will installed by Nuget?
Unfortunately, that is not possible. "LibNMeCab.IpaDicBin" installs the library and dictionary files at the same time to make it easy to use, but there are restrictions.
Instead, install "LibNMeCab" with Nuget and prepare the dictionary file separately please.

**Comment by komutan** [comment]
Or is it the situation where you have already prepared the dictionary file yourself and placed it as "Build action: contents" under the project?
In that case, the dictionary file can be output only under the build destination.
However, this isn't about NMeCab, it's about the .net compiler, so I can't explain it in detail. sorry.

**Comment by Mario1159** [comment]
Thanks, I thought It was required LibNMeCab.IpaDicBin to make the library with the dictionary work, installing LibNMeCab and preparing the dictionary file separately worked.
