### ISSUE TITLE
Can you support .net frameworks 4.5?

### ISSUE THREAD

**Issue by VShawn** [komutan/NMeCab#33]
Hi thanks for offering such a nice lib. 

I‘d like to ask if there are any plan to support .net frameworks 4.5 above?

**Comment by komutan** [comment]
@VShawn
Thank you. I'm glad you like this.

But I'm sorry. I don't have that plan.
The reason is that the life cycle of .NET FW 4.5 is over and also .NET FW 4.5.2 is no long term.

I hope one of the following...

- that it will be used with .NET FW 4.6.1 or higher (.NET Standard 2.0 compatible)
- that it will use NMeCab 0.7.0
- it will be build by changing the target FW of the NMeCab source code.

**Comment by VShawn** [comment]
> that it will be used with .NET FW 4.6.1 or higher

Actually my work was runing on .net frameworks 4.8, I mentioned 4.5 just for a greater adaptability. 

I‘m planning to port my works from .NET FW 4.8 to .NET5, but since the old version was still under maintain, can you tell me how to reference  NMeCab lib to my .NET FW 4.8 WPF app?

**Comment by komutan** [comment]
You can refer it by installing `LibNMeCab` or `LibMeMeCab.IpaDicBin` with Nuget.

https://docs.microsoft.com/nuget/quickstart/install-and-use-a-package-in-visual-studio

- https://www.nuget.org/packages/LibNMeCab
- https://www.nuget.org/packages/LibNMeCab.IpaDicBin

(`LibMeMeCab.IpaDicBin` also comes with a dictionary for Japanese analysis.)


```
using System;
using NMeCab.Specialized;

class Program
{
    static void Main()
    {
       using (var tagger = MeCabIpaDicTagger.Create()) // Taggerインスタンスを生成
       {
            var nodes = tagger.Parse("皇帝の新しい心"); // 形態素解析を実行
            foreach (var node in nodes) // 形態素ノード配列を順に処理
            {
                Console.WriteLine($"表層形：{node.Surface}");
                Console.WriteLine($"読み　：{node.Reading}");
                Console.WriteLine($"品詞　：{node.PartsOfSpeech}");
                Console.WriteLine();
            }
        }
    }
}
```

**Comment by VShawn** [comment]
Ahhh, I didn't expect it to be able to support the .NET FW 4.8 directly since it was not mentioned on the nuget.

![image](https://user-images.githubusercontent.com/10143738/111121254-61191b00-85a7-11eb-8cf2-d9d09506eebe.png)

Now it works smooth with my test demo, thank you 小牟田さん
